// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ICoreState.idl";
import "IControlSettings.idl";
import "FuzzySearchTextSegment.idl";

namespace Microsoft.Terminal.Control
{
    delegate void FuzzySearchHandler(String query);

    [default_interface] runtimeclass FuzzySearchBoxControl : Windows.UI.Xaml.Controls.UserControl, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        FuzzySearchBoxControl(IControlSettings settings, IControlAppearance unfocusedAppearance);
        void Show(String searchString);
        void SearchString(String searchString);
        event FuzzySearchHandler Search;
        void SetFontSize(Int32 width, Int32 height);
        void SetSearchResult(FuzzySearchResult val);
        event Windows.Foundation.TypedEventHandler<FuzzySearchBoxControl, Windows.UI.Xaml.RoutedEventArgs> Closed;
        event Windows.Foundation.TypedEventHandler<FuzzySearchBoxControl, FuzzySearchTextLine> OnReturn;
        Windows.UI.Xaml.Media.Brush HeaderTextColor;
        Windows.UI.Xaml.DependencyProperty HeaderTextColorProperty { get; };
        Windows.UI.Xaml.Media.Brush BorderColor;
        Windows.UI.Xaml.DependencyProperty BorderColorProperty { get; };
        Windows.UI.Xaml.Media.Brush BackgroundColor;
        Windows.UI.Xaml.DependencyProperty BackgroundColorProperty { get; };
        Windows.UI.Color SelectedItemColor;
        Windows.UI.Xaml.DependencyProperty SelectedItemColorProperty { get; };
        Windows.UI.Xaml.Thickness InnerBorderThickness;
        Windows.UI.Xaml.DependencyProperty InnerBorderThicknessProperty { get; };
        Windows.UI.Xaml.Media.Brush TextColor;
        Windows.UI.Xaml.DependencyProperty TextColorProperty { get; };
        Windows.UI.Xaml.Media.Brush HighlightedTextColor;
        Windows.UI.Xaml.DependencyProperty HighlightedTextColorProperty { get; };
    }
}
