// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "FuzzySearchTextSegment.idl";

namespace Microsoft.Terminal.Control
{
    [default_interface] runtimeclass FuzzySearchTextControl : Windows.UI.Xaml.Controls.Control
    {
        FuzzySearchTextControl();
        Windows.UI.Xaml.DependencyProperty TextProperty { get; };
        FuzzySearchTextLine Text;
        Windows.UI.Xaml.Controls.TextBlock TextView { get; };
        Windows.UI.Xaml.Media.Brush TextColor;
        Windows.UI.Xaml.DependencyProperty TextColorProperty { get; };
        Windows.UI.Xaml.Media.Brush HighlightedTextColor;
        Windows.UI.Xaml.DependencyProperty HighlightedTextColorProperty { get; };
    }
}
