// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ICoreState.idl";
import "IControlSettings.idl";
import "FuzzySearchTextSegment.idl";

namespace Microsoft.Terminal.Control
{
    delegate void FuzzySearchHandler(String query);

    [default_interface] runtimeclass FuzzySearchBoxControl : Windows.UI.Xaml.Controls.UserControl
    {
        FuzzySearchBoxControl(IControlSettings settings, IControlAppearance unfocusedAppearance);
        void Show(String searchString);
        void SearchString(String searchString);
        event FuzzySearchHandler Search;
        void SetFontSize(Int32 width, Int32 height);
        void SetSearchResult(FuzzySearchResult val);
        event Windows.Foundation.TypedEventHandler<FuzzySearchBoxControl, Windows.UI.Xaml.RoutedEventArgs> Closed;
        event Windows.Foundation.TypedEventHandler<FuzzySearchBoxControl, FuzzySearchTextLine> OnReturn;
    }
}
