// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "Search2TextSegment.idl";

namespace Microsoft.Terminal.Control
{
    delegate void SearchHandler2(String query, Boolean goForward, Boolean isCaseSensitive);

    [default_interface] runtimeclass SearchBoxControl2 : Windows.UI.Xaml.Controls.UserControl
    {
        SearchBoxControl2();
        void SetFocusOnTextbox();
        void SelectFirstItem();
        event SearchHandler2 Search;
        Boolean ContainsFocus();
        IObservableVector<Search2TextLine> ItemsSource
        {
            get;
            set;
        };
        event Windows.Foundation.TypedEventHandler<SearchBoxControl2, Windows.UI.Xaml.RoutedEventArgs> Closed;
        event Windows.Foundation.TypedEventHandler<SearchBoxControl2, Search2TextLine> SelectionChanged;
        event Windows.Foundation.TypedEventHandler<SearchBoxControl2, Search2TextLine> OnReturn;
    }
}
