// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Control
{
    struct SnippetSearchItem
    {
        String Input;
        String Description;
        String EscapedInput;
    };
}
