// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Control
{
    delegate void SuggestionInvokedHandler();

    [default_interface] runtimeclass SnippetSearchItem
    {
        SnippetSearchItem();
        SnippetSearchItem(String input, String description, String escapedInput);

        String Input;
        String Description;
        String EscapedInput;
        SuggestionInvokedHandler OnInvoked;
    }
}
