// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "FuzzySearchTextSegment.idl";
import "SnippetSearchTypes.idl";
import "TermControl.idl";

namespace Microsoft.Terminal.Control
{
    [default_interface] runtimeclass SuggestionSearchRow
    {
        FuzzySearchTextLine Line { get; };
        FuzzySearchTextLine SecondaryLine { get; };
        Boolean HasSecondaryLine { get; };
        Windows.UI.Xaml.Visibility SecondaryVisibility { get; };
        SuggestionSearchItem Item { get; };
        Windows.UI.Xaml.Media.Brush TextColor { get; };
        Windows.UI.Xaml.Media.Brush HighlightedTextColor { get; };
    }

    [default_interface] runtimeclass StreamingSuggestionsControl : Windows.UI.Xaml.Controls.UserControl, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        StreamingSuggestionsControl();
        void Open(Microsoft.Terminal.Control.TermControl termControl, String needle, Windows.Foundation.Point anchor, Windows.Foundation.Size space, String currentWord, Single prefixWidth, Single characterHeight, Single swapChainOffset);
        void OpenTasks(Microsoft.Terminal.Control.TermControl termControl, Windows.Foundation.Collections.IVector<SnippetSearchItem> snippets, Windows.Foundation.Point anchor, Windows.Foundation.Size space, String currentWord, Single prefixWidth, Single characterHeight, Single swapChainOffset);
        void OpenCommand(Microsoft.Terminal.Control.TermControl termControl, String executable, Windows.Foundation.Collections.IVector<String> args, String commandTemplate, String workingDirectory, Int32 suggestionRow, Windows.Foundation.Point anchor, Windows.Foundation.Size space, String currentWord, Single prefixWidth, Single characterHeight, Single swapChainOffset, Boolean sortResults, Boolean useCommandline);
        Boolean ContainsFocus();
        Boolean HandleKeyPress(UInt16 vkey, UInt16 scanCode, Microsoft.Terminal.Core.ControlKeyStates modifiers, Boolean keyDown);
        Windows.UI.Xaml.Media.Brush HeaderTextColor;
        Windows.UI.Xaml.DependencyProperty HeaderTextColorProperty { get; };
        Windows.UI.Xaml.Media.Brush BorderColor;
        Windows.UI.Xaml.DependencyProperty BorderColorProperty { get; };
        Windows.UI.Xaml.Media.Brush BackgroundColor;
        Windows.UI.Xaml.DependencyProperty BackgroundColorProperty { get; };
        Windows.UI.Color SelectedItemColor;
        Windows.UI.Xaml.DependencyProperty SelectedItemColorProperty { get; };
        Windows.UI.Xaml.Thickness InnerBorderThickness;
        Windows.UI.Xaml.DependencyProperty InnerBorderThicknessProperty { get; };
        Windows.UI.Xaml.Media.Brush TextColor;
        Windows.UI.Xaml.DependencyProperty TextColorProperty { get; };
        Windows.UI.Xaml.Media.Brush HighlightedTextColor;
        Windows.UI.Xaml.DependencyProperty HighlightedTextColorProperty { get; };
    }
}
